FROM openjdk:16-jdk-slim-buster
ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    WORKING_DIR='/app'

# gcc make libbz2-dev zlib1g-dev libncurses5-dev libncursesw5-dev liblzma-dev are required by htslib, samtools and bcftools
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends plink1.9 gcc make libbz2-dev zlib1g-dev libncurses5-dev libncursesw5-dev liblzma-dev \
    # install nextflow and grant permission to jupyter user jovyan
    && wget -qO- https://get.nextflow.io | bash \
    # clean up apt lists
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN pip3 install --no-cache-dir poetry==1.0.5
RUN poetry install --no-interaction --no-ansi \
    # Cleaning poetry installation's cache for production:
    && rm -rf "$POETRY_CACHE_DIR" \
    && pip uninstall -yq poetry \
    && rm -rf /tmp/* /var/cache/apk/*

# Download HTSLIB, SAMTOOLS and BCFTOOLS
WORKDIR /usr/bin
RUN wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 \
    && tar -vxjf htslib-1.9.tar.bz2 \
    && wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 \
    && tar -vxjf samtools-1.9.tar.bz2 \
    && wget https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2 \
    && tar -vxjf bcftools-1.9.tar.bz2 \
    && wget https://www.well.ox.ac.uk/~cfreeman/software/gwas/gtool_v0.7.5_x86_64.tgz \
    && tar -zxvf gtool_vX.X.X_x86_64.tgz

# Install HTSLIB
WORKDIR /usr/bin/htslib-1.9
RUN make

# Install SAMTOOLS
WORKDIR /usr/bin/samtools-1.9
RUN make

# Install BCFTools
WORKDIR /usr/bin/bcftools-1.9
RUN make

WORKDIR /app
COPY python_scripts python_scripts
COPY nextflow_pipelines/helloworld.nf nextflow_pipelines/helloworld.nf
COPY fixtures fixtures