name: Spark Job CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - master
env:
  RC_NAME: davidtnfsh/gcp_genomics
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull cache
        run: |
          docker pull ${RC_NAME}:cache

      - name: Build image
        if: always()
        run: |
          docker build --cache-from ${RC_NAME}:cache -t ${RC_NAME} .
          docker tag ${RC_NAME} ${RC_NAME}:${GITHUB_SHA}
          docker tag ${RC_NAME} ${RC_NAME}:cache
          docker tag ${RC_NAME} ${RC_NAME}:${{steps.date.outputs.date}}

      - name: Run end-to-end testing
        run: |
          # create container first
          docker run -i --rm -p 8888:8888 -e GRANT_SUDO=yes --user root ${RC_NAME} bash -c "/usr/local/spark/bin/spark-submit python_scripts/main.py"
          [ $? -eq 0 ]  || exit 1

          docker run -i --rm -p 8888:8888 -e GRANT_SUDO=yes --user root ${RC_NAME} bash -c "./nextflow run nextflow_pipelines/helloworld.nf"
          [ $? -eq 0 ]  || exit 1

      - name: Push to docker registry
        uses: actions-hub/docker@master
        with:
          args: push ${RC_NAME}:${GITHUB_SHA}

      - name: Push Cache to docker registry
        uses: actions-hub/docker@master
        if: always()
        with:
          args: push ${RC_NAME}:cache

      - name: Push to docker registry
        uses: actions-hub/docker@master
        if: github.ref == 'refs/heads/prod' && success()
        with:
          args: push ${RC_NAME}:${{steps.date.outputs.date}}